// Pre-Abatement Visual Inspection Checklist items — matches EnviroBase's form exactly

export const PRE_ABATEMENT_ITEMS = [
  { key: "area_pre_cleaned", label: "Area pre-cleaned of all debris and asbestos contamination" },
  { key: "clean_room", label: "Clean room adequate with storage for personal belongings" },
  { key: "air_handling", label: "Air handling system modified or shut off" },
  { key: "floors_two_poly", label: "Floors covered with two layers poly" },
  { key: "walls_two_poly", label: "Walls covered with two layer poly" },
  { key: "ceiling_one_poly", label: "Ceiling covered with one layer poly" },
  { key: "lights_sealed", label: "Lights removed or properly sealed" },
  { key: "edges_sealed", label: "Edges properly overlapped and sealed" },
  { key: "penetrations_sealed", label: "Penetrations sealed" },
  { key: "vents_ducts_sealed", label: "Vents, ducts, adequately sealed" },
  { key: "entry_exit_curtains", label: "All entry/exit curtains meet specification" },
  { key: "personal_decon", label: "Personal decontamination meets specification" },
  { key: "air_locks_waste", label: "Air locks sized sufficiently on waste load out" },
  { key: "equipment_room", label: "Equipment room present and adequate" },
  { key: "load_out_separated", label: "Load out area separated from personal decontamination unit" },
  { key: "smoke_tested", label: "Area smoke tested" },
  { key: "negative_pressure", label: "Negative pressure achieved" },
  { key: "manometer_measured", label: "Negative pressure measured with manometer" },
  { key: "air_exchanges", label: "Number of air exchanges per hour sufficient" },
  { key: "nams_on_site", label: "Number of NAMs on site per calculations of pressure differential" },
  { key: "hepa_nams_inspected", label: "HEPA filters or NAMs inspected" },
  { key: "make_up_air", label: "Make up air provided at other locations beyond decon" },
  { key: "danger_signs_posted", label: "Danger and warning signs posted" },
  { key: "barriers_erected", label: "Barriers erected" },
  { key: "site_security", label: "Security of site adequate" },
  { key: "shower_complete", label: "Shower construction complete and adequate" },
  { key: "hot_cold_water", label: "Hot/Cold water connected" },
  { key: "soap_towels", label: "Shampoo, soap, and towels present" },
  { key: "gray_water_working", label: "Gray water filtration system working" },
  { key: "filtration_sized", label: "Filtration sized appropriately" },
  { key: "crew_certs_match", label: "Work crew names same as worker, medical and fit certifications" },
  { key: "supervisor_cert_current", label: "Supervisor certification current and on site" },
  { key: "emergency_plan", label: "Emergency plan present" },
  { key: "fire_extinguishers", label: "Fire extinguishers in place" },
  { key: "pressure_recorders", label: "Continuous pressure recorders in place and working properly" },
  { key: "electrical_hazards", label: "Electrical hazards present" },
  { key: "lighting_adequate", label: "Lighting adequate" },
  { key: "gfci_service", label: "All electrical equipment connected to GFCI service" },
  { key: "ppe_present", label: "PPE all present including respirators and cartridges" },
  { key: "waste_bags_labeled", label: "Waste bags labeled" },
  { key: "drums_containers", label: "Sufficient drums or containers present" },
];

export const REMOVAL_TECHNIQUES = [
  { key: "wet_gross", label: "Wet/Gross" },
  { key: "glove_bag", label: "Glove/Bag" },
  { key: "primary_enclosure", label: "Primary Enclosure" },
  { key: "secondary_enclosure", label: "Secondary Enclosure" },
];
