import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireOrg } from "@/lib/org-context";

/**
 * All hardcoded task workflows defined as seedable defaults.
 * Each has a unique `defaultKey` to prevent duplicates.
 */
const DEFAULT_RULES = [
  // ── Lead Pipeline Workflows ───────────────────────────────
  {
    defaultKey: "site_visit_task",
    category: "lead_workflow",
    name: "Site Visit Task",
    trigger: "lead_status_change",
    triggerValue: "site_visit",
    taskTitle: "Site Visit - {{leadName}}",
    taskDescription:
      "Customer: {{leadName}}\nAddress: {{address}}\nScheduled: {{siteVisitDate}} at {{siteVisitTime}}\nPhone: {{phone}}\nProject Type: {{projectType}}\nNotes: {{siteVisitNotes}}",
    taskPriority: "high",
    assignToField: "worker_role",
    assignToValue: "field_estimator",
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "proposal_followup_task",
    category: "lead_workflow",
    name: "Estimate Follow-Up",
    trigger: "lead_status_change",
    triggerValue: "proposal_sent",
    taskTitle: "Estimate Follow-Up - {{leadName}}",
    taskDescription:
      "Customer: {{leadName}}\nAddress: {{address}}\nPhone: {{phone}}\nProject Type: {{projectType}}\nFollow up on estimate sent to customer.",
    taskPriority: "medium",
    assignToField: "worker_role",
    assignToValue: "desk_estimator",
    linkedEntity: true,
    dueDateOffsetDays: 3,
  },

  // ── Coordinator Tasks (Won) ───────────────────────────────
  {
    defaultKey: "coordinator_schedule_project",
    category: "coordinator",
    name: "Schedule Project",
    trigger: "lead_status_change",
    triggerValue: "won",
    taskTitle: "Schedule Project - {{leadName}}",
    taskDescription:
      "Schedule the project for {{leadName}}.\n\nAddress: {{address}}\nCompany: {{companyName}}",
    taskPriority: "high",
    assignToField: "worker_role",
    assignToValue: "project_coordinator",
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "coordinator_get_contracts",
    category: "coordinator",
    name: "Get Contracts Signed",
    trigger: "lead_status_change",
    triggerValue: "won",
    taskTitle: "Get Contracts Signed - {{leadName}}",
    taskDescription:
      "Obtain signed contracts for {{leadName}}.\n\nAddress: {{address}}\nCompany: {{companyName}}",
    taskPriority: "high",
    assignToField: "worker_role",
    assignToValue: "project_coordinator",
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "coordinator_obtain_permits",
    category: "coordinator",
    name: "Obtain Necessary Permitting",
    trigger: "lead_status_change",
    triggerValue: "won",
    taskTitle: "Obtain Necessary Permitting - {{leadName}}",
    taskDescription:
      "Secure all required permits for {{leadName}}.\n\nAddress: {{address}}\nProject Type: {{projectType}}\nCompany: {{companyName}}",
    taskPriority: "high",
    assignToField: "worker_role",
    assignToValue: "project_coordinator",
    linkedEntity: true,
    dueDateOffsetDays: null,
  },

  // ── Project Tasks: ASBESTOS ───────────────────────────────
  {
    defaultKey: "project_asbestos_cdphe_notification",
    category: "project_asbestos",
    name: "CDPHE 10-day notification",
    trigger: "project_created",
    triggerValue: "ASBESTOS",
    taskTitle: "CDPHE 10-day notification",
    taskDescription: "Submit CDPHE 10-day notification for the project.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_asbestos_pre_abatement",
    category: "project_asbestos",
    name: "Pre-abatement inspection",
    trigger: "project_created",
    triggerValue: "ASBESTOS",
    taskTitle: "Pre-abatement inspection",
    taskDescription: "Complete pre-abatement inspection for the project.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_asbestos_containment",
    category: "project_asbestos",
    name: "Containment setup",
    trigger: "project_created",
    triggerValue: "ASBESTOS",
    taskTitle: "Containment setup",
    taskDescription: "Set up containment for asbestos abatement.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_asbestos_acm_removal",
    category: "project_asbestos",
    name: "ACM removal",
    trigger: "project_created",
    triggerValue: "ASBESTOS",
    taskTitle: "ACM removal",
    taskDescription: "Remove asbestos-containing materials.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_asbestos_air_clearance",
    category: "project_asbestos",
    name: "Air clearance testing (AMS)",
    trigger: "project_created",
    triggerValue: "ASBESTOS",
    taskTitle: "Air clearance testing (AMS)",
    taskDescription: "Conduct air clearance testing with AMS.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_asbestos_waste_manifest",
    category: "project_asbestos",
    name: "Waste manifest & disposal",
    trigger: "project_created",
    triggerValue: "ASBESTOS",
    taskTitle: "Waste manifest & disposal",
    taskDescription: "Complete waste manifest and arrange disposal.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_asbestos_final_report",
    category: "project_asbestos",
    name: "Final project report to CDPHE",
    trigger: "project_created",
    triggerValue: "ASBESTOS",
    taskTitle: "Final project report to CDPHE",
    taskDescription: "Submit final project report to CDPHE.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },

  // ── Project Tasks: LEAD ───────────────────────────────────
  {
    defaultKey: "project_lead_pre_renovation",
    category: "project_lead",
    name: "Pre-renovation notification to occupants",
    trigger: "project_created",
    triggerValue: "LEAD",
    taskTitle: "Pre-renovation notification to occupants",
    taskDescription: "Send pre-renovation notification to building occupants.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_lead_inspection",
    category: "project_lead",
    name: "Lead inspection & risk assessment",
    trigger: "project_created",
    triggerValue: "LEAD",
    taskTitle: "Lead inspection & risk assessment",
    taskDescription: "Perform lead inspection and risk assessment.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_lead_relocation",
    category: "project_lead",
    name: "Occupant relocation (if needed)",
    trigger: "project_created",
    triggerValue: "LEAD",
    taskTitle: "Occupant relocation (if needed)",
    taskDescription: "Coordinate occupant relocation if required.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_lead_containment",
    category: "project_lead",
    name: "Containment & HEPA setup",
    trigger: "project_created",
    triggerValue: "LEAD",
    taskTitle: "Containment & HEPA setup",
    taskDescription: "Set up containment and HEPA filtration.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_lead_removal",
    category: "project_lead",
    name: "Lead paint removal / encapsulation",
    trigger: "project_created",
    triggerValue: "LEAD",
    taskTitle: "Lead paint removal / encapsulation",
    taskDescription: "Remove or encapsulate lead paint.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_lead_clearance_sampling",
    category: "project_lead",
    name: "Dust clearance sampling",
    trigger: "project_created",
    triggerValue: "LEAD",
    taskTitle: "Dust clearance sampling",
    taskDescription: "Conduct dust clearance sampling.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_lead_clearance_report",
    category: "project_lead",
    name: "Clearance report submission",
    trigger: "project_created",
    triggerValue: "LEAD",
    taskTitle: "Clearance report submission",
    taskDescription: "Submit clearance report.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },

  // ── Project Tasks: METH ───────────────────────────────────
  {
    defaultKey: "project_meth_law_enforcement",
    category: "project_meth",
    name: "Law enforcement report obtained",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "Law enforcement report obtained",
    taskDescription: "Obtain law enforcement report for the property.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_meth_cih_assessment",
    category: "project_meth",
    name: "CIH preliminary assessment",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "CIH preliminary assessment",
    taskDescription: "Complete CIH preliminary assessment.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_meth_assessment_sampling",
    category: "project_meth",
    name: "Assessment sampling (wipe)",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "Assessment sampling (wipe)",
    taskDescription: "Conduct wipe sampling assessment.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_meth_decon_plan",
    category: "project_meth",
    name: "Decontamination work plan",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "Decontamination work plan",
    taskDescription: "Prepare decontamination work plan.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_meth_hvac_lockout",
    category: "project_meth",
    name: "HVAC lockout & negative pressure",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "HVAC lockout & negative pressure",
    taskDescription: "Perform HVAC lockout and establish negative pressure.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_meth_surface_decon",
    category: "project_meth",
    name: "Surface decontamination",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "Surface decontamination",
    taskDescription: "Complete surface decontamination.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_meth_ventilation_decon",
    category: "project_meth",
    name: "Ventilation system decon",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "Ventilation system decon",
    taskDescription: "Decontaminate ventilation system.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_meth_post_clearance",
    category: "project_meth",
    name: "Post-decon clearance sampling",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "Post-decon clearance sampling",
    taskDescription: "Conduct post-decontamination clearance sampling.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_meth_final_report",
    category: "project_meth",
    name: "Final clearance report to governing body",
    trigger: "project_created",
    triggerValue: "METH",
    taskTitle: "Final clearance report to governing body",
    taskDescription: "Submit final clearance report to the governing body.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },

  // ── Project Tasks: MOLD ───────────────────────────────────
  {
    defaultKey: "project_mold_moisture",
    category: "project_mold",
    name: "Moisture source identification",
    trigger: "project_created",
    triggerValue: "MOLD",
    taskTitle: "Moisture source identification",
    taskDescription: "Identify and document the moisture source.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_mold_containment",
    category: "project_mold",
    name: "Containment & HEPA setup",
    trigger: "project_created",
    triggerValue: "MOLD",
    taskTitle: "Containment & HEPA setup",
    taskDescription: "Set up containment and HEPA filtration.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_mold_remediation",
    category: "project_mold",
    name: "Mold remediation",
    trigger: "project_created",
    triggerValue: "MOLD",
    taskTitle: "Mold remediation",
    taskDescription: "Perform mold remediation work.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_mold_drying",
    category: "project_mold",
    name: "Structural drying",
    trigger: "project_created",
    triggerValue: "MOLD",
    taskTitle: "Structural drying",
    taskDescription: "Complete structural drying.",
    taskPriority: "medium",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_mold_verification",
    category: "project_mold",
    name: "Post-remediation verification",
    trigger: "project_created",
    triggerValue: "MOLD",
    taskTitle: "Post-remediation verification",
    taskDescription: "Verify remediation work is complete and effective.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
  {
    defaultKey: "project_mold_clearance",
    category: "project_mold",
    name: "Clearance sampling (IEP)",
    trigger: "project_created",
    triggerValue: "MOLD",
    taskTitle: "Clearance sampling (IEP)",
    taskDescription: "Conduct clearance sampling by IEP.",
    taskPriority: "high",
    assignToField: "none",
    assignToValue: null,
    linkedEntity: true,
    dueDateOffsetDays: null,
  },
];

export async function POST() {
  const result = await requireOrg();
  if (result instanceof NextResponse) return result;
  const { session } = result;
  const userRole = (session.user as any)?.role;
  if (userRole === "TECHNICIAN") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  let seeded = 0;

  for (const rule of DEFAULT_RULES) {
    // Check if already seeded by defaultKey
    const existing = await prisma.taskAutomationRule.findFirst({
      where: { defaultKey: rule.defaultKey },
    });
    if (existing) continue;

    await prisma.taskAutomationRule.create({
      data: {
        ...rule,
        isDefault: true,
        enabled: true,
      },
    });
    seeded++;
  }

  return NextResponse.json({ seeded, total: DEFAULT_RULES.length });
}
